service: cms-booking-handler

frameworkVersion: "2"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

plugins:
  - serverless-webpack
  - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /booking
        method: post
        queueName: !GetAtt BookingQueue.QueueName
        cors: false
        response:
          template:
            success: |-
              { "message": "Notification received" }
            clientError: |-
              { "message": "There is an error in your request" }
            serverError: |-
              { "message": "There was an error handling your request" }
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

package:
  individually: true

functions:
  bookingWorker: ${file(./serverless/lambda.yml):BookingWorker}

resources:
  Resources:
    BookingQueue: ${file(./serverless/sqs.yml):BookingQueue}
    BookingsQueueDLQ: ${file(./serverless/sqs.yml):BookingsQueueDLQ}
