BookingQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: "BookingsQueue"
    MessageRetentionPeriod: 1209600
    VisibilityTimeout: 60
    RedrivePolicy:
      deadLetterTargetArn:
        Fn::GetAtt:
          - BookingsQueueDLQ
          - Arn
      maxReceiveCount: 1
BookingsQueueDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: "BookingsQueueDLQ"
    MessageRetentionPeriod: 1800
